export const GET_FACULTIES_REQUEST = 'GET_FACULTIES_REQUEST'
export const GET_FACULTIES_SUCCESS = 'GET_FACULTIES_SUCCESS'
export const GET_FACULTIES_FAILED = 'GET_FACULTIES_FAILED'

export const GET_DIRECTIONS_OF_FACULTY_REQUEST = 'GET_DIRECTIONS_OF_FACULTY_REQUEST'
export const GET_DIRECTIONS_OF_FACULTY_SUCCESS = 'GET_DIRECTIONS_OF_FACULTY_SUCCESS'
export const GET_DIRECTIONS_OF_FACULTY_FAILED = 'GET_DIRECTIONS_OF_FACULTY_FAILED'

export const GET_TIME_REQUEST = 'GET_TIME_REQUEST'
export const GET_TIME_SUCCESS = 'GET_TIME_SUCCESS'
export const GET_TIME_FAILED = 'GET_TIME_FAILED'
